In [29]:
import pandas as pd
import sklearn.utils.stats as stats
import os
import numpy as np
from scipy.stats.contingency import chi2_contingency

In [2]:
os.environ['KAGGLEHUB_CACHE'] = os.curdir

if not os.path.isdir('datasets'):
    import kagglehub
    path = kagglehub.dataset_download("faviovaz/marketing-ab-testing")
else:
    path = os.path.join('datasets','faviovaz','marketing-ab-testing','versions','1')
    
path = os.path.join(path, 'marketing_AB.csv')
print("Path to dataset files:", path)

Path to dataset files: datasets\faviovaz\marketing-ab-testing\versions\1\marketing_AB.csv

In [15]:
df = pd.read_csv(path).drop('Unnamed: 0', axis = 1)
df

        user id test group  converted  total ads most ads day  most ads hour
0       1069124         ad      False        130       Monday             20
1       1119715         ad      False         93      Tuesday             22
2       1144181         ad      False         21      Tuesday             18
3       1435133         ad      False        355      Tuesday             10
4       1015700         ad      False        276       Friday             14
...         ...        ...        ...        ...          ...            ...
588096  1278437         ad      False          1      Tuesday             23
588097  1327975         ad      False          1      Tuesday             23
588098  1038442         ad      False          3      Tuesday             23
588099  1496395         ad      False          1      Tuesday             23
588100  1237779         ad      False          1      Tuesday             23

[588101 rows x 6 columns]

In [16]:
df['test group'].value_counts()

test group
ad     564577
psa     23524
Name: count, dtype: int64

In [19]:
grouped_df = df.groupby('test group').agg({'converted':'sum', 'total ads':'sum', 'most ads hour':'mean'})
grouped_df

            converted  total ads  most ads hour
test group
ad              14423   14014701      14.475900
psa               420     582481      14.304923

In [22]:
grouped_df['total ads']['ad']

np.int64(14014701)

In [ ]:
ad_total, psa_total = grouped_df['total ads']['ad'], grouped_df['total ads']['psa']
ad_conv, psa_conv = grouped_df['converted']['ad'], grouped_df['converted']['psa']

In [ ]:
table = np.array([
    [ad_conv, ad_total - ad_conv],
    [psa_conv, psa_total - psa_conv]
])

# Table Shape                 
# ad converted, ad not converted
# psa converted, psa not converted

table

array([[   14423, 14000278],
       [     420,   582061]])

In [48]:
p = chi2_contingency(table).pvalue
p

np.float64(5.692168097674627e-13)

In [64]:
alpha = 0.05

print('There is a significant difference' if alpha > p else 'There is not enough evidence')

There is a significant difference